numpy funciones matematicas 
pandas
matplotlib

In [1]:
!pip install numpy

You should consider upgrading via the 'C:\Users\facki\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Funciones de Numpy argmax()-argmin()/Max-min en Python 
sqrt() Para sacar la raiz cuadrada 

In [2]:
import numpy as np

In [3]:
print ("Hola")

Hola


In [4]:
import sys

#### Creando una lista

In [5]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Pasando de lista a un Array
Array es una funcion de numpy

In [6]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Crear una lista de solo numeros unos

In [7]:
unos = np.ones(24)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [8]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
type(ceros)

numpy.ndarray

In [10]:
arreglo.dtype

dtype('int64')

In [11]:
lista2 = ["Ian", 22, True]
lista2

['Ian', 22, True]

In [12]:
arreglo2 = np.array(lista2)
arreglo2

array(['Ian', '22', 'True'], dtype='<U21')

### Consultando la cantidad de memoria ocupada

In [13]:
memoria_lista = sys.getsizeof(lista)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memorua ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memorua ocupada por el array: 80 bytes


### Promedio del arreglo

In [14]:
promedio = np.mean(lista)
promedio

np.float64(5.5)

In [15]:
new_arreglo = arreglo.astype(np.float64)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Aplicando el paquete random

Se genera una lista de numeros enteros aleatorios, que van desde el numero que le deseamos escoger

In [16]:
np.random.randint(10)

7

In [17]:
np.random.randint(1,100)

82

In [18]:
np.random.rand(1,10,4)

array([[[0.5871505 , 0.54217255, 0.21397657, 0.31151642],
        [0.823683  , 0.24494205, 0.35821397, 0.91845469],
        [0.9575466 , 0.80888694, 0.40862301, 0.61722488],
        [0.78261205, 0.61960391, 0.67671591, 0.83079381],
        [0.51564342, 0.30368271, 0.37675134, 0.17111396],
        [0.00758133, 0.70103462, 0.13375968, 0.43127607],
        [0.73235356, 0.16190822, 0.39250387, 0.91930878],
        [0.63031528, 0.86199018, 0.04100205, 0.81754198],
        [0.7449614 , 0.42853482, 0.17221007, 0.95038434],
        [0.38194838, 0.01727763, 0.14103871, 0.08803967]]])