numpy funciones matematicas 
pandas
matplotlib

In [33]:
!pip install numpy

You should consider upgrading via the 'C:\Users\facki\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


Funciones de Numpy argmax()-argmin()/Max-min en Python 
sqrt() Para sacar la raiz cuadrada 

In [34]:
import numpy as np

In [35]:
print ("Hola")

Hola


In [36]:
import sys

#### Creando una lista

In [37]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Pasando de lista a un Array
Array es una funcion de numpy

In [38]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Crear una lista de solo numeros unos

In [39]:
unos = np.ones(24)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [40]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [41]:
type(ceros)

numpy.ndarray

In [42]:
arreglo.dtype

dtype('int64')

In [43]:
lista2 = ["Ian", 22, True]
lista2

['Ian', 22, True]

In [44]:
arreglo2 = np.array(lista2)
arreglo2

array(['Ian', '22', 'True'], dtype='<U21')

### Consultando la cantidad de memoria ocupada

In [47]:
memoria_lista = sys.getsizeof(lista)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memorua ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memorua ocupada por el array: 80 bytes


### Promedio del arreglo

In [48]:
promedio = np.mean(lista)
promedio

np.float64(5.5)

In [50]:
new_arreglo = arreglo.astype(np.float64)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Aplicando el paquete random

Se genera una lista de numeros enteros aleatorios, que van desde el numero que le deseamos escoger

In [68]:
np.random.randint(10)

6

In [79]:
np.random.randint(1,100)

48

In [80]:
np.random.rand(1,10,4)

array([[[0.30843673, 0.06102313, 0.84418143, 0.80421685],
        [0.44665096, 0.28242252, 0.7352561 , 0.76532604],
        [0.69145968, 0.77781139, 0.04748844, 0.25535047],
        [0.23610394, 0.29670508, 0.59224209, 0.58207767],
        [0.92437061, 0.10788844, 0.72143478, 0.5812764 ],
        [0.4064796 , 0.05096862, 0.65574317, 0.76895397],
        [0.83784523, 0.78902675, 0.78844844, 0.92236445],
        [0.23740875, 0.9456734 , 0.24840289, 0.14571954],
        [0.97759956, 0.32557521, 0.95809616, 0.62155025],
        [0.9983631 , 0.84669411, 0.37605202, 0.56212319]]])